name: 2024

on:
  push:
    branches: ["main"]
    paths:
      - "apps/2024/**"
      - ".github/workflows/2024.yml"
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "apps/2024/**"
      - ".github/workflows/2024.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: pnpm --filter=2024 exec pnpm dlx @cloudflare/next-on-pages@1

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/2024
          command: pages deploy .vercel/output/static --project-name=2024
          packageManager: pnpm

      - name: Print Deployment URL
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
