name: Admin

on:
  push:
    branches: ["main"]
    paths:
      - "apps/admin/**"
      - ".github/workflows/admin.yml"
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "apps/admin/**"
      - ".github/workflows/admin.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: pnpm run build --filter=admin
        env:
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          VITE_ADMIN_AFTER_SIGN_IN_URL: ${{ secrets.ADMIN_AFTER_SIGN_IN_URL}}
          VITE_ADMIN_AFTER_SIGN_UP_URL: ${{ secrets.ADMIN_AFTER_SIGN_UP_URL}}
          VITE_ADMIN_SIGN_IN_URL: ${{ secrets.ADMIN_SIGN_IN_URL}}
          VITE_ADMIN_SIGN_UP_URL: ${{ secrets.ADMIN_SIGN_UP_URL}}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/admin
          command: pages deploy dist --project-name=knighthacks-admin
          packageManager: pnpm
