name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "packages/api/**"
      - ".github/workflows/api.yml"

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./packages/api
          command: deploy
          packageManager: pnpm
