name: API

on:
  push:
    branches: ["main"]
    paths:
      - "packages/api/**"
      - ".github/workflows/api.yml"
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./packages/api
          command: deploy
          packageManager: pnpm
