name: API

on:
  push:
    branches: ["main"]
    paths:
      - "packages/api/**"
      - ".github/workflows/api.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./packages/api
          command: deploy
          packageManager: pnpm
          secrets: |
            DATABASE_URL
            DATABASE_AUTH_TOKEN
            DEV_DATABASE_URL
            DEV_DATABASE_AUTH_TOKEN
            CLERK_SECRET_KEY
            CLERK_PUBLISHABLE_KEY
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          DEV_DATABASE_URL: ${{ vars.DEV_DATABASE_URL }}
          DEV_DATABASE_AUTH_TOKEN: ${{ secrets.DEV_DATABASE_AUTH_TOKEN }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ vars.CLERK_PUBLISHABLE_KEY }}
