name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "apps/socials-bot/**"
      - ".github/workflows/bot.yml"

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/socials-bot
          command: deploy
          packageManager: pnpm
