name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        env:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm run deploy
